packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: "19.2.3"
  react-dom: "19.2.3"
  "@types/react": "^19.2.0"
  "@types/react-dom": "^19.2.0"

  typescript: "^5.9.3"
  "@types/node": "^25.0.10"

  tailwindcss: "^4"
  "@tailwindcss/postcss": "^4"
  "@tailwindcss/typography": "^0.5.20"
  "@tailwindcss/vite": "^4"
  tailwind-merge: "^3.4.0"
  class-variance-authority: "^0.7.1"
  clsx: "^2.1.1"

  lucide-react: "^1.0.1"

  vitest: "^4.1.0"
  jsdom: "^29.0.1"
  "@vitejs/plugin-react": "^6.0.1"
  "@testing-library/react": "^16.3.2"
  "@testing-library/jest-dom": "^6.9.1"
  "@testing-library/user-event": "^14.6.1"